<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Andy Field" />


<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>adventr: hypothesis testing</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-an-adventure-in-r-hypothesis-testing" class="section level1">
<h1>An Adventure in R: Hypothesis testing</h1>
<div id="section-overview" class="section level2">
<h2>Overview</h2>
<p>This tutorial is one of a series that accompanies <a href="https://www.discoveringstatistics.com/books/an-adventure-in-statistics/">An Adventure in Statistics</a> <span class="citation">(Field 2016)</span> by me, <a href="https://en.wikipedia.org/wiki/Andy_Field_(academic)">Andy Field</a>. These tutorials contain abridged sections from the book so there are some copyright considerations but I offer them under a <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>,<a href="#section-fn1" class="footnote-ref" id="section-fnref1"><sup>1</sup></a></p>
<ul>
<li>Who is the tutorial aimed at?
<ul>
<li>Anyone teaching from or reading <a href="https://www.discoveringstatistics.com/books/an-adventure-in-statistics/">An Adventure in Statistics</a> may find them useful.</li>
</ul></li>
<li>What is covered?
<ul>
<li>This tutorial looks at how to compute effect sizes and Bayes factors for a basic research design that compares two groups. It would be a useful tutorial to run alongside teaching based on Chapter 11 of <a href="https://www.discoveringstatistics.com/books/an-adventure-in-statistics/">An Adventure in Statistics</a>.</li>
<li>This tutorial <em>does not</em> teach the background theory: it is assumed you have either attended my lecture or read the relevant chapter in the aforementioned books (or someone else’s)</li>
<li>The aim of this tutorial is to augment the theory that you already know by guiding you through fitting linear models using <strong>R</strong> and <strong>RStudio</strong> and asking you questions to test your knowledge along the way.</li>
</ul></li>
</ul>
</div>
<div id="section-story-précis" class="section level2">
<h2>Story précis</h2>
<div id="section-why-a-précis" class="section level3">
<h3>Why a précis?</h3>
<p>Because these tutorials accompany my book <em>An adventure in statistics</em>, which uses a fictional narrative to teach the statistics, some of the examples might not make sense unless you know something about the story. For those of you who don’t have the book I begin each tutorial with a précis of the story. If you’re not interested then fair enough - click past this section.</p>
</div>
<div id="section-general-context-for-the-story" class="section level3">
<h3>General context for the story</h3>
<p>It is the future. Zach, a rock musician and Alice, a geneticist, who have been together since high school live together in Elpis, the ‘City of Hope’.</p>
<p>Zach and Alice were born in the wake of the Reality Revolution which occurred after a Professor Milton Gray invented the Reality Prism – a transparent pyramid worn on the head – that brought honesty to the world. Propaganda and media spin became unsustainable, religions collapsed, advertising failed. Society could no longer be lied to. Everyone could know the truth about anything that they could look at. A gift, some said, to a previously self-interested, self-obsessed society in which the collective good had been eroded.</p>
<p>But also a curse. For, it soon became apparent that through this Reality Prism, people could no longer kid themselves about their own puffed-up selves as they could see what they were really like – by and large, pretty ordinary. And this caused mass depression. People lost faith in themselves. Artists abandoned their pursuits, believing they were untalented and worthless.</p>
<p>Zach and Alice have never worn a Reality Prism and have no concept of their limitations. They were born after the World Governance Agency (WGA) destroyed all Reality Prisms, along with many other pre-revolution technologies, with the aim of restoring community and well-being. However, this has not been straightforward and in this post-Prism world, society has split into pretty much two factions</p>
<ul>
<li>The Chippers who have had WiFi-enabled chips implanted into their brains, enabling them to record and broadcast what they see and think in real time; upload memories for future generations into a newly-created memoryBank and live-stream music and films directly into their brains.</li>
<li>The Clocktarians, followers of the old pre-Prism ways who use steam punk style technologies, who have elected not to have chips in their brains, regarded by the Chippers as backward-looking stuck in a ‘clockwork, Victorian society’.</li>
</ul>
<p>Everyone has a star, a limitless space on which to store their digital world.</p>
<p>Zach and Alice are Clocktarians. Their technology consists mainly of:</p>
<ul>
<li>A Proteus, a device made from programmable matter that can transform shape and function simply by the owners’ wishes. Zach calls his a diePad, in the shape of a tombstone in an ironic reference to an over-reliance on technology at the expense of memory.</li>
<li>A Reality Checker, a clockwork mechanism that, at the point of critical velocity, projects an opaque human head that is linked to everything and can tell you anything. Every head has a personality and Zach’s is a handsome, laid back ‘dude’ who is like an electronic friend, who answers questions if he feels like it and often winds Zach up by giving him false information. And he often flirts with Alice.</li>
</ul>
</div>
<div id="section-main-protagonists" class="section level3">
<h3>Main Protagonists</h3>
<ul>
<li>Zach
<ul>
<li>Rock musician in band called The Reality Enigma.</li>
<li>Spellbinding performer, has huge fan-base.</li>
<li>Only people living in Elpis get to see The Reality Enigma in the flesh. Otherwise all performances are done via an oculus riff, a multisensory headset for experiencing virtual gigs.</li>
<li>Zach’s music has influenced and changed thousands of lives.</li>
<li>Wishes he had lived pre-Revolutionary times, the turn of the 21st Century, a golden age for music when bands performed in reality at festivals.</li>
<li>Kind, gentle and self-doubting.</li>
<li>Believes science and maths are dull and uninspiring. Creates a problem between him and Alice as she thinks that because he isn’t interested in science, he isn’t interested in her. Leads to lots of misunderstandings between them.</li>
</ul></li>
<li>Alice
<ul>
<li>Shy, lonely, academically-gifted – estranged from the social world until she met Zach in the college library.</li>
<li>Serious scientist, works at the Beimeni Centre of Genetics.</li>
<li>At 21, won the World Science Federation’s Einstein Medal for her genetics research</li>
<li>Desperately wants Zach to get over his fear of science so he can open his mind to the beauty of it.</li>
</ul></li>
</ul>
</div>
<div id="section-how-zachs-adventure-begins" class="section level3">
<h3>How Zach’s adventure begins</h3>
<p>Alice has been acting strangely, on edge for weeks, disconnected and uncommunicative, as if she is hiding something and Zach can’t get through to her. Arriving home from band practice, unusually, she already home and listening to an old album that the two of them enjoyed together, back in a simpler, less complicated time in their relationship. During an increasingly testy evening, that involves a discussion with the Head about whether or not a Proteus causes brain cancer, Alice is interrupted by an urgent call which she takes in private. She returns looking worried and is once again, distracted. She tells Zach that she has ‘a big decision to make’. Before going to bed, Zach asks her if he can help with the decision but she says he ‘already has’, thanking him for making ‘everything easier.’ He has no idea what she means and goes to sleep, uneasy.</p>
<p>On waking, Zach senses that something is wrong. And he is right. Alice has disappeared. Her clothes, her possessions and every photo of them together have gone. He can’t get hold of any of her family or friends as their contact information is stored on her Proteus, not on his diePad. He manages to contact the Beimeni Centre but is told that no one by the name of Alice Nightingale has ever worked there. He logs into their constellation but her star has gone. He calls her but finds that her number never existed. She has, thinks Zach, been ‘wiped from the planet.’ He summons The Head but he can’t find her either. He tells Zach that there are three possibilities: Alice has doesn’t want to be found, someone else doesn’t want her to be found or she never existed.</p>
<p>Zach calls his friend Nick, fellow band member and fan of the WGA-installed Repositories, vast underground repositories of actual film, books, art and music. Nick is a Chipper – solely for the purpose of promoting the band using memoryBank – and he puts the word out to their fans about Alice missing.</p>
<p>Thinking as hard as he can, Zach recalls the lyrics of the song she’d been playing the previous evening. Maybe they are significant? It may well be a farewell message and the Head is right. In searching for clues, he comes across a ‘memory stone’ which tells him to read what’s on there. File 1 is a research paper that Zach can’t fathom. It’s written in the ‘language of science’ and the Head offers to help Zach translate it and tells him that it looks like the results of her current work were ‘gonna blow the world’. Zach resolves to do ‘something sensible’ with the report.</p>
<p>Zach doesn’t want to believe that Alice has simply just left him. Rather, that someone has taken her and tried to erase her from the world. He decides to find her therapist, Dr Murali Genari and get Alice’s file. As he breaks into his office, Dr Genari comes up behind him and demands to know what he is doing. He is shaking but not with rage – with fear of Zach. Dr Genari turns out to be friendly and invites Zach to talk to him. Together they explore the possibilities of where Alice might have gone and the likelihood, rating her relationship satisfaction, that she has left him. During their discussion Zach is interrupted by a message on his diePad from someone called Milton. Zach is baffled as to who he is and how he knows that he is currently discussing reverse scoring. Out of the corner of his eye, he spots a ginger cat jumping down from the window ledge outside. The counsellor has to go but suggests that Zach and ‘his new friend Milton’ could try and work things out.</p>
</div>
</div>
<div id="section-packages-and-data" class="section level2">
<h2>Packages and data</h2>
<div id="section-packages" class="section level3">
<h3>Packages</h3>
<p>This tutorial uses the following packages:</p>
<ul>
<li><code>BayesFactor</code> <span class="citation">(Morey and Rouder 2014)</span> to compute Bayes factors</li>
<li><code>effsize</code> <span class="citation">(Torchiano 2017)</span> to compute Cohen’s <em>d</em></li>
<li><code>Hmisc</code> <span class="citation">(Harrell 2017)</span> to compute confidence intervals</li>
<li><code>tidyverse</code> <span class="citation">(Wickham 2017)</span> for general data processing</li>
</ul>
<p>These packages are automatically loaded within this tutorial. If you are working outside of this tutorial (i.e. in <strong>RStudio</strong>) then you need to make sure that the package has been installed by executing <code>install.packages("package_name")</code>, where <em>package_name</em> is the name of the package. If the package is already installed, then you need to reference it in your current session by executing <code>library(package_name)</code>, where <em>package_name</em> is the name of the package.</p>
</div>
<div id="section-data" class="section level3">
<h3>Data</h3>
<p>This tutorial has the data files pre-loaded so you shouldn’t need to do anything to access the data from within the tutorial. However, if you want to play around with what you have learnt in this tutorial outside of the tutorial environment (i.e. in a stand-alone <strong>RStudio</strong> session) you will need to download the data files and then read them into your <strong>R</strong> session. This tutorial uses the following file:</p>
<ul>
<li><a href="http://www.discoveringstatistics.com/repository/ais_data/ais_10_teddy_therapy.csv">ais_10_teddy_therapy.csv</a>.</li>
<li><a href="http://www.discoveringstatistics.com/repository/ais_data/ais_15_puzz_zhang_female.csv">ais_15_puzz_zhang_female.csv</a>.</li>
</ul>
<p>You can load the files in several way (using the first file as an example):</p>
<ul>
<li>Assuming that you follow the workflow recommended in the tutorial <strong>adventr_02</strong> (see also this <a href="http://milton-the-cat.rocks/learnr/r/r_getting_started/#section-working-in-rstudio">online tutorial</a>), you can load the data into an object called <code>teddy_tib</code> by executing:
<ul>
<li><code>teddy_tib &lt;- readr::read_csv("../data/ais_10_teddy_therapy.csv")</code></li>
<li>If you don’t follow my suggested workflow, you will adjust the file location in the above command.</li>
</ul></li>
<li>Alternatively, if you have an internet connection (and my server has not exploded!) load the file direct from the URL by executing:
<ul>
<li><code>teddy_tib &lt;- readr::read_csv("http://www.discoveringstatistics.com/repository/ais_data/ais_10_teddy_therapy.csv")</code></li>
</ul></li>
</ul>
<p>Adapt the above instructions to load the second data file into a tibble called <code>zhang_female_tib</code>.</p>
</div>
</div>
<div id="section-a-cuddly-example" class="section level2">
<h2>A cuddly example</h2>
<p>Zach has just escaped from the Secret Philanthropic Society, who seem to do bizarre rituals that involve their members shoving their hands into boxes that may or may not contain a lethal gernal worm. They use probability to determine whether the box will be empty. He meets Emily, the member whose ritual he witnessed. She is riddled with doubts about the societies methods, but is powerless to escape. With Zach’s help she does, and they are led by a strange moon-faced druid into a tombstone. It’s never a good idea idea to follow moon-faced druids into tombstones. Nevertheless they do. He encounters the Doctrine of Chance led by Sister Price. They explain alternative methods to test evidence: specifically effect sizes and Bayes factors.</p>
<p>We’re going to use the data in the tibble called <code>teddy_tib</code>, which contains data from two studies looking at whether cuddling a teddy bear (compared to the cardboard box that the teddy was packaged in) affects self-reported self-esteem. This tibble contains 4 variables:</p>
<ul>
<li><strong>id</strong>: Participant ID</li>
<li><strong>group</strong>: whether the participant cuddled a teddy bear or the cardboard box that contained the teddy bear</li>
<li><strong>study_n</strong>: Factor that distinguishes the two studies in the data set. The first was based on a total <em>N</em> of 20 and the second was based on a total <em>N</em> of 200</li>
<li><strong>self_esteem</strong>: Self-reported self-esteem scores</li>
</ul>
<p>Using what you have learnt to date, can you create a tibble called <code>teddy_sum</code> containing the means, standard deviations and confidence intervals for each group across the two studies. (If you’re doing this outside of the tutorial remember to load <em>tidyverse</em> <span class="citation">(Wickham 2017)</span> and <em>Hmisc</em> <span class="citation">(Harrell 2017)</span>).</p>
<div class="tutorial-exercise" data-label="teddy_means" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="6">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="teddy_means-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_sum &lt;- teddy_tib %&gt;%
  dplyr::group_by(study_n, group) %&gt;%
  dplyr::summarize(
    mean = mean(self_esteem),
    sd = sd(self_esteem),
    ci_low = ggplot2::mean_cl_normal(self_esteem)$ymin,
    ci_upp = ggplot2::mean_cl_normal(self_esteem)$ymax
    )</code></pre>
</div>
<p>Now try plotting an error bar graph using <code>facet_wrap()</code> to display graphs for the two studies side by side. use <code>coord_cartesian()</code> to set the <em>y</em>-limits to be 0-20, <code>scale_y_continuous()</code> to set ticks along the axis every two (e.g., 0, 2, 4, 6 ….), and <code>labs()</code> to define labels foe the <em>x</em>- and <em>y</em>-axes.</p>
<div class="tutorial-exercise" data-label="teddy_mean_plot" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="teddy_mean_plot-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>ted_plot &lt;- ggplot2::ggplot(teddy_tib, aes(group, self_esteem))
ted_plot +
  stat_summary(fun.data = &quot;mean_cl_normal&quot;, size = 1) +
  facet_wrap(~ study_n) +
  coord_cartesian(ylim = c(0,20)) + 
  scale_y_continuous(breaks = seq(0, 20, 2)) +
  labs(x = &quot;Experimental condition&quot;, y = &quot;Self-esteem (0-20)&quot;) +
  theme_bw()</code></pre>
</div>
</div>
<div id="section-effect-sizes" class="section level2">
<h2>Effect sizes</h2>
<div id="section-cohens-d" class="section level3">
<h3>Cohen’s <em>d</em></h3>
<p>A useful measure of effect size is Cohen’s <em>d</em>, which is the difference between two means divided by some estimate of the standard deviation of those means:</p>
<p><span class="math display">\[
\hat{d} = \frac{\bar{X_1}-\bar{X_2}}{s}
\]</span></p>
<p>I have put a hat on the <em>d</em> to remind us that we’re really interested in the effect size in the population, but because we can’t measure that directly, we estimate it from the samples (The hat means ‘estimate of’). By dividing by the standard deviation we are expressing the difference in means in standard deviation units (a bit like a <em>z</em>–score). The standard deviation is a measure of ‘error’ or ‘noise’ in the data, so <em>d</em> is effectively a signal-to-noise ratio. However, if we’re using two means, then there will be a standard deviation associated with each of them so which one should we use? There are three choices:</p>
<ol style="list-style-type: decimal">
<li>If one of the group is a control group it makes sense to use that groups standard deviation to compute <em>d</em> (the argument being that the experimental manipulation might affect the standard deviation of the experimental group, so the control group <em>SD</em> is a ‘purer’ measure of natural variation in scores)</li>
<li>Sometimes we assume that group variances (and therefore standard deviations) are equal (homogeneity of variance) and if they are we can pick a standard deviation from either of the groups because it won’t matter.</li>
<li>We use what’s known as a ‘pooled estimate’, which is the weighted average of the two group variances. This is given by the following equation:</li>
</ol>
<p><span class="math display">\[
s_p = \sqrt{\frac{(N_1-1) s_1^2+(N_2-1) s_2^2}{N_1+N_2-2}}
\]</span></p>
<p>Say we wanted to estimate <em>d</em> for the difference between self-esteem after cuddling the teddy compared to the box (control), assuming you successfully created the tibble (<code>teddy_sum</code>) then you should have this information:</p>
<table>
<caption>Summary statistics for the teddy and box groups within the two experiments</caption>
<thead>
<tr class="header">
<th align="left">study_n</th>
<th align="left">group</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">ci_low</th>
<th align="right">ci_upp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Total N = 20</td>
<td align="left">Box</td>
<td align="right">10</td>
<td align="right">5.962848</td>
<td align="right">5.734436</td>
<td align="right">14.26556</td>
</tr>
<tr class="even">
<td align="left">Total N = 20</td>
<td align="left">Teddy Bear</td>
<td align="right">15</td>
<td align="right">6.018490</td>
<td align="right">10.694632</td>
<td align="right">19.30537</td>
</tr>
<tr class="odd">
<td align="left">Total N = 200</td>
<td align="left">Box</td>
<td align="right">10</td>
<td align="right">5.962848</td>
<td align="right">8.816842</td>
<td align="right">11.18316</td>
</tr>
<tr class="even">
<td align="left">Total N = 200</td>
<td align="left">Teddy Bear</td>
<td align="right">15</td>
<td align="right">5.978074</td>
<td align="right">13.813820</td>
<td align="right">16.18618</td>
</tr>
</tbody>
</table>
<p>We have a logical control group so <em>d</em> is simply:</p>
<p><span class="math display">\[
\hat{d}_\text{teddy vs box} = \frac{15-10}{5.96} = 0.839
\]</span></p>
<p>If we use the pooled <em>s</em> then we’d get:</p>
<p><span class="math display">\[
\begin{aligned}
  \ s_p &amp;= \sqrt{\frac{(N_1-1) s_1^2+(N_2-1) s_2^2}{N_1+N_2-2}} \\
  \ &amp;= \sqrt{\frac{(10-1)5.96^2+(10-1)6.02^2}{10+10-2}} \\
  \ &amp;= \sqrt{\frac{645.86}{18}} \\
  \ &amp;= 5.99
\end{aligned}
\]</span></p>
<p>Basically, because the group standard deviations are more or less the same (5.96 and 6.02) the pooled estimate is very similar too (it falls between those two values). Consequently, the resulting effect size is not going to change much when we use the pooled estimate:</p>
<p><span class="math display">\[
\hat{d}_\text{teddy vs box} = \frac{15-10}{5.99} = 0.835
\]</span></p>
<p>Let’s look at computing Cohen’s <em>d</em> using the pooled estimate in <strong>R</strong>. We’re going to do this separately for the two studies in out tibble (<code>teddy_tib</code>). As a brief recap, this tibble contains 4 variables:</p>
<ul>
<li><strong>id</strong>: Participant ID</li>
<li><strong>group</strong>: whether the participant cuddled a teddy bear or the cardboard box that contained the teddy bear</li>
<li><strong>study_n</strong>: Factor that distinguishes the two studies in the data set. The first was based on a total <em>N</em> of 20 and the second was based on a total <em>N</em> of 200. We’re going to use this variable to <code>dplyr::filter()</code> the tibble before we compute <em>d</em>.</li>
<li><strong>self_esteem</strong>: Self-reported self-esteem scores</li>
</ul>
<p>Like many things in <strong>R</strong>, there are numerous packages that offer functions to compute effect sizes. We’re going to use the <code>cohen.d()</code> function from the <code>effsize</code> package <span class="citation">(Torchiano 2017)</span> primarily because it computes it from the raw data (rather than from summary statistics) and because it has an option to compute it in designs that use repeated measures (i.e. the means across conditions are dependent). The general format of this function is:</p>
<p><code>cohen.d(formula = outcome ~ group_variable, pooled = TRUE, paired = FALSE, na.rm = FALSE, hedges.correction = FALSE, conf.level = 0.95)</code></p>
<p>The arguments within this function are:</p>
<ul>
<li><code>formula = outcome ~ group_variable</code>: this allows us to specify the outcome variable (in this case <strong>self_esteem</strong>) and the variable that defines the two groups (in this case <strong>group</strong>). This format of specifying a model as <code>outcome ~ predictor</code> will become very familiar to you as we progress through these tutorials.</li>
<li><code>pooled = TRUE</code>: by default the pooled standard deviation, <span class="math inline">\(s_p\)</span>, will be used. If you set this option to FALSE then the standard deviation of the whole sample will be used. Typically you’d leave this option alone (i.e., use the pooled estimate).</li>
<li><code>paired = FALSE</code>: by default the function considers scores as coming from different entities (i.e. an independent designs). That’s the design our teddy bear experiments use. However, if you have a repeated measures design (i.e. in our example participants cuddle both a teddy and a box at different points in time) then set paired to TRUE.</li>
<li><code>na.rm = FALSE</code>: we’ve seen this option before. By default missing values are not removed and you should set this option to TRUE if you have missing values.</li>
<li><code>hedges.correction = FALSE</code>: the option determines whether a correction is applied to <em>d</em>. This converts <em>d</em> to something called Hedges’ <em>g</em>. By default the option isn’t applied, but it is a good to apply it.</li>
<li><code>conf.level = 0.95</code>: by default the confidence interval will be a 95% one, but you can adjust this option to change the width of the confidence interval. The default is fine.</li>
</ul>
<p>The function returns an object that contains the value of <em>d</em>, the confidence interval and some other information. We’re going to use a pipe (<code>%&gt;%</code>) to link:</p>
<ul>
<li><code>teddy_tib</code>: our input will be the tibble of raw data</li>
<li><code>dplyr::filter(study_n == "Total N = 20")</code>: we’re going to filter that tibble to extract the experiment based on a sample size of 20</li>
<li><code>cohen.d()</code> the function described above will compute the effect size.</li>
</ul>
<pre class="r"><code>teddy_tib %&gt;%
  dplyr::filter(study_n == &quot;Total N = 20&quot;) %&gt;%
  effsize::cohen.d(formula = self_esteem ~ group, data = .)</code></pre>
<p>This command takes the <code>teddy_tib</code> tibble, extracts the study based on 20 participants, then applies the <code>cohen.d()</code> function. Within this function we have left the defaults as they are, our formula specifies that we’re predicting <strong>self_esteem</strong> from the variable <strong>group</strong> (which defines whether the individual hugs a teddy or a box), and we specify the data within the function with a period (<code>data = .</code>). By using a period we’re telling the function to use the data coming through from the pipe. Copy this command in the code box below and run the code. Then edit it to apply Hedges’ correction, then edit the code again to get the effect size for the experiment that had 200 participants.</p>
<div class="tutorial-exercise" data-label="try_d" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="try_d-hint" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># To get the Hedges&#39; correction we&#39;d add hedges.correction = T:

teddy_tib %&gt;%
  dplyr::filter(study_n == &quot;Total N = 20&quot;) %&gt;%
  effsize::cohen.d(formula = self_esteem ~ group, data = ., hedges.correction = T)

# To get effectsizes we&#39;d change the filter() function to extract the study based on 200 participants:

teddy_tib %&gt;%
  dplyr::filter(study_n == &quot;Total N = 200&quot;) %&gt;%
  effsize::cohen.d(formula = self_esteem ~ group, data = ., hedges.correction = T)</code></pre>
</div>
<p>Applying the Hedges’ correction to both studies, we’d get these outputs:</p>
<pre><code>## 
## Hedges&#39;s g
## 
## g estimate: -0.7993566 (medium)
## 95 percent confidence interval:
##      lower      upper 
## -1.7344640  0.1357508</code></pre>
<pre><code>## 
## Hedges&#39;s g
## 
## g estimate: -0.8342794 (large)
## 95 percent confidence interval:
##      lower      upper 
## -1.1239409 -0.5446178</code></pre>
<p>This shows that for the smaller study, the effect of cuddling a teddy compared to a box on self-esteem was <em>g</em> = -0.80 [-1.78, 0.18]. Whether <em>d</em> (or <em>g</em>) has a positive or negative sign reflects which way around you subtracted the group means. The teddy group had a mean of 15 and and box group a mean of 10. The difference between these means will be 5 if you subtract the box mean from the teddy mean (15 - 10 = 5), but -5 if you subtract the teddy mean from the box mean (10 - 15 = -5). So, to interpret the effect size look at the group means (not the plus of minus sign of <em>g</em>). In this case, self-esteem is 0.80 of a standard deviation higher after cuddling a teddy than after cuddling a box. The confidence interval for this effect size suggests (if we assume this sample is one of the 95% that contain the population value) that the population effect could range between -1.78 and 0.18. Crucially this means the effect could be 0, and could reflect higher self-esteem in the box group OR in the teddy group.</p>
<div class="panel panel-default">
<div data-label="ci_quiz" class="tutorial-question panel-body">
<div id="ci_quiz-answer_container" class="shiny-html-output"></div>
<div id="ci_quiz-message_container" class="shiny-html-output"></div>
<div id="ci_quiz-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
<div id="section-an-optional-tricky-section" class="section level3">
<h3>An optional tricky section</h3>
<p>I’ve struggled to find a function that will automatically calculate <em>d</em> using the standard deviation of the control group. However, it is simple enough to get <strong>R</strong> to subtract two values and then divide by another value. For example, to add <em>x</em> and <em>y</em> and then divide by <em>z</em> you could execute <code>(x + y)/z</code>. Simple. What’s not simple is re-arranging the data so that we have the group means in columns. It can be done but involves restructuring the data in a crazy pipe involving lots of functions that we haven’t learnt! I’m going to just plough through how it’s done, explain what everything does but not cover the new functions in detail. So, by all means ignore this section if you like.</p>
<p>Earlier we created a tibble called <code>teddy_sum</code> that includes the means, standard deviations and confidence intervals of those means. The problem is that the means and <em>sd</em>s for the box and teddy groups are in different rows and we want them in different columns so that we can subtract them. This is to remind you of what the tibble currently contains:</p>
<table>
<caption>Summary statistics for the teddy and box groups within the two experiments</caption>
<thead>
<tr class="header">
<th align="left">study_n</th>
<th align="left">group</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">ci_low</th>
<th align="right">ci_upp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Total N = 20</td>
<td align="left">Box</td>
<td align="right">10</td>
<td align="right">5.962848</td>
<td align="right">5.734436</td>
<td align="right">14.26556</td>
</tr>
<tr class="even">
<td align="left">Total N = 20</td>
<td align="left">Teddy Bear</td>
<td align="right">15</td>
<td align="right">6.018490</td>
<td align="right">10.694632</td>
<td align="right">19.30537</td>
</tr>
<tr class="odd">
<td align="left">Total N = 200</td>
<td align="left">Box</td>
<td align="right">10</td>
<td align="right">5.962848</td>
<td align="right">8.816842</td>
<td align="right">11.18316</td>
</tr>
<tr class="even">
<td align="left">Total N = 200</td>
<td align="left">Teddy Bear</td>
<td align="right">15</td>
<td align="right">5.978074</td>
<td align="right">13.813820</td>
<td align="right">16.18618</td>
</tr>
</tbody>
</table>
<p>I’m going to restructure this tibble so that all of the information from a given experiment is in a single row (that is, create columns contain the means, <em>sd</em>s and confidence intervals for each group). That’s the hard part. Then I will add a column that compotes <em>d</em> (that’s the easy part!).</p>
<p>Restructuring data using the <em>tidyverse</em> package <em>tidyr</em> is something that I find endlessly confusing, so if you find it confusing too then don’t worry - you’re in good company! To restructure the data we’re going to use this pipe:</p>
<pre class="r"><code>teddy_wide &lt;-  teddy_sum %&gt;%
  tidyr::gather(measure, value, -c(study_n, group)) %&gt;%
  tidyr::unite(gp_measure, group, measure) %&gt;% 
  tidyr::spread(gp_measure, value)</code></pre>
<p>It’s a pipe that could carry gas across the Atlantic. Let’s break it down.</p>
<ul>
<li><code>teddy_sum %&gt;%</code>: we begin with the <code>teddy_sum</code> tibble and carry that into the next function using the pipe operator (<code>%&gt;%</code>).</li>
<li><code>tidyr::gather(measure, value, -c(study_n, group))</code>: this takes each variable in <code>teddy_sum</code> and places its value in a variable called <strong>value</strong> (you can name it what you like, I chose ‘value’) and creates a variable called <strong>measure</strong> (again, you can name it differently) in which it identifies to what the value relates. For example, the if the value is from the column <strong>mean</strong> then the value placed in <strong>measure</strong> will be the word ‘mean’. Crucially, I have used <code>-c(study_n, group)</code> to exclude the variables <strong>study_n</strong> and <strong>group</strong> from this process. These variables retain their existing values. To get a feel for what’s happening execute the pipe just to this point in the code box (i.e., execute <code>teddy_sum %&gt;% tidyr::gather(measure, value, -c(study_n, group))</code>). Essentially the variables <strong>mean</strong>, <strong>sd</strong>, <strong>ci_low</strong> and <strong>ci_upp</strong> which were in 4 columns have been replaced by two columns: one (<strong>measure</strong>) contains the name of the original column and the other (<strong>value</strong>) contains the value.</li>
<li><code>tidyr::unite(gp_measure, group, measure)</code> is used to unite the variables <strong>group</strong> and <strong>measure</strong> into a single variable called <strong>gp_measure</strong> (again, choose a different name if you like). It basically combines the values from the columns and separates them with an underscore. For example, if the value of <strong>group</strong> is <em>Box</em> and the value of <strong>measure</strong> is <em>mean</em> then the resulting value in <strong>gp_measure</strong> will be <em>Box_mean</em>. In effect, we’re creating a variable to contain column names to use when we transform the data back. Again, if you want to see what’s going on use the code box to run the pipe up to this point (<code>teddy_sum %&gt;% tidyr::gather(measure, value, -c(study_n, group)) %&gt;% tidyr::unite(gp_measure, group, measure)</code>).</li>
<li><code>tidyr::spread(gp_measure, value)</code>: Finally, we spread the data back out into separate columns using <strong>gp_measure</strong> to define the column names and <strong>value</strong> to define the values placed with each column.</li>
</ul>
<div class="tutorial-exercise" data-label="ted_restruc" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ted_restruc-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_wide &lt;-  teddy_sum %&gt;%
  tidyr::gather(measure, value, -c(study_n, group)) %&gt;%
  tidyr::unite(gp_measure, group, measure) %&gt;% 
  tidyr::spread(gp_measure, value)
teddy_wide</code></pre>
</div>
<p>Run the full pipe to create this new tibble (which I’ve called <code>teddy_wide</code>). Execute the name of the tibble to look at it. The resulting tibble contains these variables</p>
<ul>
<li><strong>study_n</strong>: Factor that distinguishes the two studies in the data set. The first was based on a total <em>N</em> of 20 and the second was based on a total <em>N</em> of 200.</li>
<li><strong>Box_ci_low</strong>: lower limit of the confidence interval in the box group.</li>
<li><strong>Box_ci_upp</strong>: upper limit of the confidence interval in the box group.</li>
<li><strong>Box_mean</strong>: mean self-esteem in the box group.</li>
<li><strong>Box_sd</strong>: standard deviation of self-esteem in the box group.</li>
<li><strong>`Teddy Bear_ci_low`</strong>: lower limit of the confidence interval in the teddy group.</li>
<li><strong>`Teddy Bear_ci_upp`</strong>: upper limit of the confidence interval in the teddy group.</li>
<li><strong>`Teddy Bear_mean`</strong>: mean self-esteem in the teddy group.</li>
<li><strong>`Teddy Bear_sd`</strong>: standard deviation of self-esteem in the teddy group.</li>
</ul>
<p>The variables for the teddy bear group have been named a bit clunkily (because we’d defined the group as ‘Teddy Bear’). Let’s tidy these names up using the <code>rename()</code> function:</p>
<pre class="r"><code>teddy_wide &lt;- teddy_wide %&gt;%
  rename(
   teddy_ci_low = `Teddy Bear_ci_low`,
   teddy_ci_upp = `Teddy Bear_ci_upp`,
   teddy_mean = `Teddy Bear_mean`,
   teddy_sd = `Teddy Bear_sd`
  )</code></pre>
<p>This code recreates the <code>teddy_wide</code> tibble from itself but creates a variable <strong>teddy_ci_low</strong> from the variable currently called <strong>`Teddy Bear_ci_low`</strong> and do on. In effect I’m renaming the ‘Teddy Bear’ variables to omit spaces and remove upper case letters (and be shorter). Try this in the code box and inspect the resulting tibble.</p>
<div class="tutorial-exercise-support" data-label="ted_rename-setup" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_wide &lt;-  teddy_sum %&gt;%
  tidyr::gather(measure, value, -c(study_n, group)) %&gt;%
  tidyr::unite(gp_measure, group, measure) %&gt;%
  tidyr::spread(gp_measure, value)</code></pre>
</div>
<div class="tutorial-exercise" data-label="ted_rename" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ted_rename-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_wide &lt;- teddy_wide %&gt;%
  rename(
   teddy_ci_low = `Teddy Bear_ci_low`,
   teddy_ci_upp = `Teddy Bear_ci_upp`,
   teddy_mean = `Teddy Bear_mean`,
   teddy_sd = `Teddy Bear_sd`
  )
teddy_wide</code></pre>
</div>
<p>Well done if you’re still with me! Let’s now do the (relatively) easy bit. Now we have the group means in columns, it’s relatively straightforward to use <code>mutate()</code> to add a column that contains <em>d</em>:</p>
<pre class="r"><code>teddy_wide &lt;- teddy_wide %&gt;%
  dplyr::mutate(
  d = (teddy_mean - Box_mean)/Box_sd
)</code></pre>
<p>This code re-creates the <code>teddy_wide</code> tibble from itself, but then uses <code>mutate()</code> to add a variable called <strong>d</strong>, which is defined as <code>(teddy_mean - Box_mean)/Box_sd</code>. In other words it subtracts the scores in the column <strong>Box_mean</strong> from the scores in the column <strong>teddy_mean</strong> and divides the result by the scores in the column <strong>Box_sd</strong>. In other words, it takes the difference between the group means and divides by the standard deviation for the control group! Try this below and then view the resulting tibble to see the values of <em>d</em>.</p>
<div class="tutorial-exercise-support" data-label="ted_d-setup" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_wide &lt;-  teddy_sum %&gt;%
  tidyr::gather(measure, value, -c(study_n, group)) %&gt;%
  tidyr::unite(gp_measure, group, measure) %&gt;%
  tidyr::spread(gp_measure, value)

teddy_wide &lt;- teddy_wide %&gt;%
  rename(
   teddy_ci_low = `Teddy Bear_ci_low`,
   teddy_ci_upp = `Teddy Bear_ci_upp`,
   teddy_mean = `Teddy Bear_mean`,
   teddy_sd = `Teddy Bear_sd`
  )</code></pre>
</div>
<div class="tutorial-exercise" data-label="ted_d" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ted_d-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_wide &lt;- teddy_wide %&gt;%
  dplyr::mutate(
  d = (teddy_mean - Box_mean)/Box_sd
)
teddy_wide</code></pre>
</div>
<div class="panel panel-default">
<div data-label="d_quiz" class="tutorial-question panel-body">
<div id="d_quiz-answer_container" class="shiny-html-output"></div>
<div id="d_quiz-message_container" class="shiny-html-output"></div>
<div id="d_quiz-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
</div>
<div id="section-bayes-factors" class="section level2">
<h2>Bayes factors</h2>
<div id="section-bayes-factors-and-priors" class="section level3">
<h3>Bayes factors and priors</h3>
<p>The Bayes factor quantifies the probability of the data given the alternative hypothesis (in this case that self-esteem differs in the teddy and box groups) relative to the probability of the data given the null hypothesis (in this case that self-esteem is the same in the teddy and box groups):</p>
<p><span class="math display">\[
\text{Bayes factor} = \frac{p(\text{data}|\text{alternative})}{p(\text{data}|\text{null})} \\
\]</span></p>
<p>The Bayesian t-test uses a default prior distribution based on a value, <em>r</em>, which scales the distribution <span class="citation">(Rouder et al. 2009)</span>. The advantage of this approach is that it enables people to use a Bayesian method without needing to choose a prior from an almost endless set of possibilities. By con straining the decisions, some of the hard thinking is removed. The disadvantage is that defaults can tempt people to use them without any thought, and it’s tricky to understand what’s going on under the hood. To encourage you to give some thought to your prior, let’s look under the hood (just a bit). The prior distribution is constrained to be from a family known as the Cauchy distribution. Members of the Cauchy family look a bit like a normal distributions, but they’re not. Figure 1 shows Cauchy distributions with different scale factors, <em>r</em>: that are medium, <em>r</em> = 0.5 (left); wide, <em>r</em> = 0.7071 (middle), and ultrawide, <em>r</em> = 1 (right). Each curve has a shaded region with boundaries from −r to +r and the region under the curve between these boundaries represents 50% of the area. Note that the width of this region gets wider as <em>r</em> increases. When you set the value of <em>r</em> you are assigning a 50% probability that the effect size (Cohen’s <em>d</em>) lies between −<em>r</em> and +<em>r</em>. Given the distribution is symmetrical, you’re also assigning a 25% prior belief that <em>d</em> is greater than <em>r</em> and the remaining 25% that <em>d</em> is less than −<em>r</em>.</p>
<p>If you use the default value of <em>r</em> = 0.7071 you are, therefore, saying that your prior belief is that there’s a 50% probability that the effect size (Cohen’s <em>d</em>) lies between −0.7071 and +0.7071, a 25% probability that it is greater than +0.7071 and a 25% probability that it is less than −0.7071. Remembering what <em>d</em> represents, you’re saying that there’s a 50% probability that the difference between the two means lies between −0.7071 and +0.7071 standard deviations. If you set <em>r</em> = 0.5 (Figure 1, left) the Cauchy distribution becomes narrower and you are similarly narrowing your prior beliefs to a 50% probability that the difference between the group means lies between −0.5 and +0.5 standard deviations. Setting <em>r</em> = 1 (Figure 1, right) widens the distribution, representing wider beliefs. You’d be placing a 50% probability that the difference between the group means lies between −1 and +1 standard deviations. Remembering that <em>d</em> = 0.8 is a large effect, you’d be assigning a 50% probability to the difference between means being somewhere between a very large effect in one direction and a very large effect in the opposite direction. This is too wide a belief for most situations (bearing in mind that another 50% of the probability is assigned to the effect being outside those limits).</p>
<div class="figure">
<img src="images/cauchys.png" alt="" />
<p class="caption">Figure 1: Distributions representing the <em>r</em> scale</p>
</div>
</div>
<div id="section-bayes-factors-in-r" class="section level3">
<h3>Bayes factors in <strong>R</strong></h3>
<p>The <code>BayesFactor</code> package contains various functions for computing Bayes factors. We’ll use it at various points for other models. For now, we’ll use the <code>ttestBF()</code> function, which is designed for situations where you want a Bayes factor that quantifies differences between two means. It has a general form of:</p>
<p><code>ttestBF(formula = outcome ~ group_variable, mu = 0, paired = FALSE, data = NULL, rscale = "medium")</code></p>
<p>It has some other arguments not listed above, but these are the key ones for our purposes:</p>
<ul>
<li><code>formula = outcome ~ group_variable</code>: this allows us to specify the outcome variable (in this case <strong>self_esteem</strong>) and the variable that defines the two groups (in this case <strong>group</strong>). This is basically the same as the <code>cohen.d()</code> function.</li>
<li><code>mu = 0</code>: for this example we can ignore this but if you want to use the function on a one-sample or paired design then you can use this to specify the null value of the mean (or mean difference in a paired design). The default of 0 is usually what you would want.</li>
<li><code>paired = FALSE</code>: by default the function considers scores as coming from different entities (i.e. an independent designs). That’s the design our teddy bear experiments use. However, if you have a repeated measures design (i.e. in our example participants cuddle both a teddy and a box at different points in time) then set paired to TRUE.</li>
<li><code>data = Null</code>: use this option to specify the tibble containing the data.</li>
<li><code>rscale = "medium"</code>: This option specifies the prior. You can input a numeric value or use one of three pre-defined default priors. These defaults are “medium”, “wide”, and “ultrawide”, which correspond to values of sqrt(2)/2 (i.e., 0.707), 1, and sqrt(2) respectively. I explained these priors earlier.</li>
</ul>
<p>Like when we computed an effect size we’re going to use a pipe (<code>%&gt;%</code>) to link:</p>
<ul>
<li><code>teddy_tib</code>: our input will be the tibble of raw data</li>
<li><code>dplyr::filter(study_n == "Total N = 20")</code>: we’re going to filter that tibble to extract the experiment based on a sample size of 20</li>
<li><code>ttestBF()</code> the function described above will compute the Bayes factor.</li>
</ul>
<pre class="r"><code>teddy_tib %&gt;%
  dplyr::filter(study_n == &quot;Total N = 20&quot;) %&gt;%
  BayesFactor::ttestBF(formula = self_esteem ~ group, data = .)</code></pre>
<p>This command takes the <code>teddy_tib</code> tibble, extracts the study based on 20 participants, then applies the <code>ttestBF()</code> function. You’ll get a warning about data coerced from a atibble to a dataframe because the function works with dataframes so it converts your tibble to a data frame. The warning is nothing to worry about.</p>
<p>Within this function we have left the defaults as they are (i.e. a ‘medium’ prior scale value of 0.707), our formula specifies that we’re predicting <strong>self_esteem</strong> from the variable <strong>group</strong> (which defines whether the individual hugs a teddy or a box), and we specify the data within the function with a period (<code>data = .</code>). By using a period we’re telling the function to use the data coming through from the pipe. Copy this command in the code box below and run the code. Then edit it to get the Bayes factor for the experiment that had 200 participants.</p>
<div class="tutorial-exercise" data-label="try_bf" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="try_bf-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>teddy_tib %&gt;%
  dplyr::filter(study_n == &quot;Total N = 200&quot;) %&gt;%
  BayesFactor::ttestBF(formula = self_esteem ~ group, data = .)</code></pre>
</div>
<p>The resulting Bayes factor is 1.27 which means that the probability of the data given the alternative hypothesis is about the same as the probability of the data given the null. The value here suggests that we should not change our prior beliefs. By using the default prior we assigned a 50% probability to the effect size (<em>d</em>) lying between −0.7071 and +0.7071, and this Bayes factor tells us not to change this belief.</p>
<p>For the larger sample the Bayes factor is 754768.4, which is huge. The probability of the data given the alternative hypothesis is 754768.4 greater than the probability of the data given the null. The value here suggests that we should shift our prior beliefs towards the alternative hypothesis by a factor of 754768.4. In other words, having looked at the data we should hold a very much stronger belief that the means are different.</p>
<p>Remember that the effect sizes in the two studies were basically identical, so it may seem strange that the Bayes factors are so different. However, if you think about it, Bayesian methods update prior beliefs using the data. A small amount of data will have less impact on beliefs than a huge sample (if the priors are the same). Imagine you’re asked the probability that a sports team will win their next game. You guess at 33% change that they’ll win (you assume win, lose or draw are equally likely). Take two scenarios: you’re told that this team won their last game. This might increase your belief in a win, but probably not by much - perhaps that game was a fluke. The second scenario is that you’re told that they have won their last 20 games. You’re belief in a win will probably shift quite strongly towards a win - they have consistently shown a winning mentality. In both cases you’re being told that they have won 100% of past games, but in the first case that is based on a tiny amount of data, in the latter case it’s based on a lot of date. This illustrates the principle of how (other things being equal) larger data sets have increasing influence.</p>
<div class="panel panel-default">
<div data-label="bf_quiz" class="tutorial-question panel-body">
<div id="bf_quiz-answer_container" class="shiny-html-output"></div>
<div id="bf_quiz-message_container" class="shiny-html-output"></div>
<div id="bf_quiz-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
</div>
</div>
<div id="section-concluding-task" class="section level2">
<h2>Concluding task</h2>
<p>The tibble <code>zhang_female_tib</code> contains a small random subsample of females from a study that looked at performance on a maths test when the test is taken under the participant’s own name, or a fake name. There are two variables:</p>
<ul>
<li><strong>name</strong>: Specifies whether participants completed the test under their own name or a fake name</li>
<li><strong>accuracy</strong>: Accuracy on the maths test (%)</li>
</ul>
<p>In the code box, produce some code to:</p>
<ul>
<li>Produce an error bar plot of the two group means and their confidence intervals</li>
<li>Hedges <em>g</em> for the difference between mean accuracy scores in the two groups</li>
</ul>
<div class="tutorial-exercise" data-label="task" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="8">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="task-solution" data-caption="Exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>zhang_plot &lt;- ggplot2::ggplot(zhang_female_tib, aes(name, accuracy))
zhang_plot +
  stat_summary(fun.data = &quot;mean_cl_normal&quot;, size = 1) +
  coord_cartesian(ylim = c(0,100)) + 
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  labs(x = &quot;Experimental condition&quot;, y = &quot;Accuracy on maths test (%)&quot;) +
  theme_bw()

#to get g:
zhang_female_tib %&gt;%
  effsize::cohen.d(formula = accuracy ~ name, data = ., hedges.correction = T)

#to get a Bayes factor:

zhang_female_tib %&gt;%
  BayesFactor::ttestBF(formula = accuracy ~ name, data = .)</code></pre>
</div>
</div>
<div id="section-other-resources" class="section level2">
<h2>Other resources</h2>
<div id="section-statistics" class="section level3">
<h3>Statistics</h3>
<ul>
<li>The tutorials typically follow examples described in detail in <span class="citation">Field (2016)</span>, so for most of them there’s a thorough account in there. You might also find <span class="citation">Field, Miles, and Field (2012)</span> useful for the <strong>R</strong> stuff.</li>
<li>There are free lectures and screen casts on my <a href="https://www.youtube.com/user/ProfAndyField/">YouTube channel</a></li>
<li>There are free statistical resources on my website <a href="http://www.discoveringstatistics.com">www.discoveringstatistics.com</a></li>
</ul>
</div>
<div id="section-r" class="section level3">
<h3>R</h3>
<ul>
<li>Information on using <a href="http://ggplot2.tidyverse.org/">ggplot2</a></li>
<li><a href="http://r4ds.had.co.nz/index.html">R for data science</a> is the open-access version of the book by tidyverse creator Hadley Wickham <span class="citation">(Wickham and Grolemund 2017)</span>. It covers the <em>tidyverse</em> and data management.</li>
<li><a href="http://moderndive.com/index.html">ModernDive</a> is an open-access textbook on <strong>R</strong> and <strong>RStudio</strong></li>
<li><a href="https://www.rstudio.com/resources/cheatsheets/">RStudio cheat sheets</a></li>
<li><a href="https://www.rstudio.com/online-learning/">RStudio list of online resources</a></li>
<li><a href="http://swirlstats.com/students.html">SwirlStats</a> is a package for <em>R</em> that launches a bunch of interactive tutorials.</li>
</ul>
</div>
</div>
<div id="section-references" class="section level2">
<h2>References</h2>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
library(tidyverse)
library(BayesFactor)
library(effsize)


knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
tutorial_options(exercise.cap = "Exercise")

#Read dat files needed for the tutorial

teddy_tib <- adventr::teddy_dat;
zhang_female_tib <- adventr::zhang_female_dat

#setup objects for code blocks

teddy_sum <- teddy_tib %>% dplyr::group_by(study_n, group) %>% dplyr::summarize(
  mean = mean(self_esteem),
  sd = sd(self_esteem),
  ci_low = ggplot2::mean_cl_normal(self_esteem)$ymin,
  ci_upp = ggplot2::mean_cl_normal(self_esteem)$ymax
)

</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-teddy_means-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-teddy_means-code-editor`)), session)
output$`tutorial-exercise-teddy_means-output` <- renderUI({
  `tutorial-exercise-teddy_means-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-teddy_mean_plot-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-teddy_mean_plot-code-editor`)), session)
output$`tutorial-exercise-teddy_mean_plot-output` <- renderUI({
  `tutorial-exercise-teddy_mean_plot-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-try_d-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-try_d-code-editor`)), session)
output$`tutorial-exercise-try_d-output` <- renderUI({
  `tutorial-exercise-try_d-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "ci_quiz", question = structure("In the larger study the confidence interval ranged from -1.13 to -0.54. What does this tell us?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_875f38c",     option = "If this confidence interval is one of the 95% that contains the population value then the population value of the difference between group means lies between -1.13 to -0.54.",     value = "If this confidence interval is one of the 95% that contains the population value then the population value of the difference between group means lies between -1.13 to -0.54.",     label = structure("If this confidence interval is one of the 95% that contains the population value then the population value of the difference between group means lies between -1.13 to -0.54.", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_39e2f87",     option = "There is a 95% chance that the population value of the difference between group means lies between -1.13 to -0.54.",     value = "There is a 95% chance that the population value of the difference between group means lies between -1.13 to -0.54.",     label = structure("There is a 95% chance that the population value of the difference between group means lies between -1.13 to -0.54.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("You cannot make probability statements from a confidence interval. We don&#39;t know whether this particular CI is one of the 95% that contains the population value of the difference between means.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_63f4c3f", option = "The probability of this confidence interval containing the population value is 0.95.",     value = "The probability of this confidence interval containing the population value is 0.95.",     label = structure("The probability of this confidence interval containing the population value is 0.95.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("The probability of this confidence interval containing the population value is either 0 (it doesn&#39;t) or 1 (it does) but it&#39;s impossible to know which.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_5ac01cd", option = "I can be 95% confident that the population value of the difference between group means lies between -1.13 to -0.54.",     value = "I can be 95% confident that the population value of the difference between group means lies between -1.13 to -0.54.",     label = structure("I can be 95% confident that the population value of the difference between group means lies between -1.13 to -0.54.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("Confidence intervals do not quantify your subjective confidence.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct - well done!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "ci_quiz-answer", question = "ci_quiz"), loading = structure("<strong>Loading:<\u002fstrong> \nIn the larger study the confidence interval ranged from -1.13 to -0.54. What does this tell us?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1209529769.93677, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ted_restruc-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ted_restruc-code-editor`)), session)
output$`tutorial-exercise-ted_restruc-output` <- renderUI({
  `tutorial-exercise-ted_restruc-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ted_rename-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ted_rename-code-editor`)), session)
output$`tutorial-exercise-ted_rename-output` <- renderUI({
  `tutorial-exercise-ted_rename-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ted_d-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ted_d-code-editor`)), session)
output$`tutorial-exercise-ted_d-output` <- renderUI({
  `tutorial-exercise-ted_d-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "d_quiz", question = structure("Which of these statements about Cohen&#39;s <em>d<\u002fem> is <strong>NOT<\u002fstrong> correct?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_ddce81a",     option = "The value of *d* cannot exceed 1.", value = "The value of *d* cannot exceed 1.",     label = structure("The value of <em>d<\u002fem> cannot exceed 1.", html = TRUE, class = c("html",     "character")), correct = TRUE, message = structure("This statement is false and so is the coirrect answer.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ba967d", option = "*d* is the difference between two means expressed in standard deviation units.",     value = "*d* is the difference between two means expressed in standard deviation units.",     label = structure("<em>d<\u002fem> is the difference between two means expressed in standard deviation units.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("This statement is true so is not the correct answer.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_1631206", option = "A *d* of 0.2 would be considered small",     value = "A *d* of 0.2 would be considered small", label = structure("A <em>d<\u002fem> of 0.2 would be considered small", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("This statement is true so is not the correct answer.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_24f4162", option = "*d* can be computed using a control group standard deviation, the standard deviation of all scores or a pooled standard deviation.",     value = "*d* can be computed using a control group standard deviation, the standard deviation of all scores or a pooled standard deviation.",     label = structure("<em>d<\u002fem> can be computed using a control group standard deviation, the standard deviation of all scores or a pooled standard deviation.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("This statement is true so is not the correct answer.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct - well done!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "d_quiz-answer", question = "d_quiz"), loading = structure("<strong>Loading:<\u002fstrong> \nWhich of these statements about Cohen&#39;s <em>d<\u002fem> is <strong>NOT<\u002fstrong> correct?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 1913673201.10888, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-try_bf-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-try_bf-code-editor`)), session)
output$`tutorial-exercise-try_bf-output` <- renderUI({
  `tutorial-exercise-try_bf-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "bf_quiz", question = structure("What is a Bayes factor??", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_47a6f9e",     option = "The relative probability of the data given the alternative to the data given the null.",     value = "The relative probability of the data given the alternative to the data given the null.",     label = structure("The relative probability of the data given the alternative to the data given the null.", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_314e5dc",     option = "The ratio of the probability of the alternative hypothesis given the data to the probability of the null hypothesis given the data.",     value = "The ratio of the probability of the alternative hypothesis given the data to the probability of the null hypothesis given the data.",     label = structure("The ratio of the probability of the alternative hypothesis given the data to the probability of the null hypothesis given the data.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("This statement describes the posterior odds.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_8abd251", option = "The ratio of the probability of the alternative hypothesis to the probability of the null hypothesis.",     value = "The ratio of the probability of the alternative hypothesis to the probability of the null hypothesis.",     label = structure("The ratio of the probability of the alternative hypothesis to the probability of the null hypothesis.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("This statement describes the prior odds.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_7b5f845", option = "Tell me a terrible and possible inappropriate joke about Bayesians.",     value = "Tell me a terrible and possible inappropriate joke about Bayesians.",     label = structure("Tell me a terrible and possible inappropriate joke about Bayesians.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("Q. Why do Bayesians make good proctologists? A. Because they&#39;re always looking at the posterior.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct - well done!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "bf_quiz-answer", question = "bf_quiz"), loading = structure("<strong>Loading:<\u002fstrong> \nWhat is a Bayes factor??\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = TRUE, allow_retry = TRUE,     seed = 536187822.250318, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-task-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-task-code-editor`)), session)
output$`tutorial-exercise-task-output` <- renderUI({
  `tutorial-exercise-task-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106]}},"value":[{"type":"character","attributes":{},"value":["acepack","adventr","assertthat","backports","base","base64enc","BayesFactor","broom","cellranger","checkmate","cli","cluster","coda","colorspace","compiler","crayon","data.table","datasets","DBI","dbplyr","digest","dplyr","effsize","ellipsis","evaluate","fansi","fastmap","forcats","foreign","Formula","fs","generics","ggplot2","glue","graphics","grDevices","grid","gridExtra","gtable","gtools","haven","highr","Hmisc","hms","htmlTable","htmltools","htmlwidgets","httpuv","httr","jpeg","jsonlite","knitr","later","lattice","latticeExtra","learnr","lifecycle","lubridate","magrittr","markdown","Matrix","MatrixModels","methods","mime","modelr","munsell","mvtnorm","nnet","parallel","pbapply","pillar","pkgconfig","png","promises","purrr","R6","RColorBrewer","Rcpp","readr","readxl","reprex","rlang","rmarkdown","rpart","rprojroot","rstudioapi","rvest","scales","shiny","splines","stats","stringi","stringr","survival","tibble","tidyr","tidyselect","tidyverse","tools","utils","vctrs","withr","xfun","xml2","xtable","yaml"]},{"type":"character","attributes":{},"value":["1.4.1","0.1.8","0.2.1","1.1.6","4.0.0","0.1-3","0.9.12-4.2","0.7.0.9000","1.1.0","2.0.0","2.0.2","2.1.0","0.19-3","1.4-1","4.0.0","1.3.4","1.12.8","4.0.0","1.1.0","1.4.3","0.6.25","0.8.5","0.8.0","0.3.0","0.14","0.4.1","1.0.1","0.5.0","0.8-79","1.2-3","1.4.1","0.0.2","3.3.0","1.4.0","4.0.0","4.0.0","4.0.0","2.3","0.3.0","3.8.2","2.2.0","0.8","4.4-0","0.5.3","1.13.3","0.4.0","1.5.1","1.5.2","1.4.1","0.1-8.1","1.6.1","1.28","1.0.0","0.20-41","0.6-29","0.10.1","0.2.0","1.7.8","1.5","1.1","1.2-18","0.4-1","4.0.0","0.9","0.1.7","0.5.0","1.1-0","7.3-14","4.0.0","1.4-2","1.4.4","2.0.3","0.1-7","1.1.0","0.3.4","2.4.1","1.1-2","1.0.4.6","1.3.1","1.3.1","0.3.0","0.4.6","2.1","4.1-15","1.3-2","0.11","0.3.5","1.1.1","1.4.0.2","4.0.0","4.0.0","1.4.6","1.4.0","3.1-12","3.0.1","1.0.3","1.1.0","1.3.0","4.0.0","4.0.0","0.3.0","2.2.0","0.13","1.3.2","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
<div id="section-refs" class="references">
<div id="section-ref-RN10163">
<p>Field, Andy P. 2016. <em>An Adventure in Statistics: The Reality Enigma</em>. Book. London: Sage.</p>
</div>
<div id="section-ref-RN4832">
<p>Field, Andy P., Jeremy N. V. Miles, and Zoe C. Field. 2012. <em>Discovering Statistics Using R: And Sex and Drugs and Rock ’N’ Roll</em>. Book. London: Sage.</p>
</div>
<div id="section-ref-RN11417">
<p>Harrell, F E. 2017. “Hmisc: A Package of Miscellaneous R Functions.” Journal Article. <em>R Package Version 4.0-3</em>. <a href="https://CRAN.R-project.org/package=Hmisc">https://CRAN.R-project.org/package=Hmisc</a>.</p>
</div>
<div id="section-ref-RN9444">
<p>Morey, Richard D., and Jeffrey N. Rouder. 2014. “BayesFactor: Computation of Bayes Factors for Common Designs.” Journal Article R package version 0.9.9. <a href="%20http://CRAN.R-project.org/package=BayesFactor">http://CRAN.R-project.org/package=BayesFactor</a>.</p>
</div>
<div id="section-ref-RN9316">
<p>Rouder, Jeffrey N., Paul L. Speckman, Dongchu Sun, Richard D. Morey, and Geoffrey Iverson. 2009. “Bayesian T Tests for Accepting and Rejecting the Null Hypothesis.” Journal Article. <em>Psychonomic Bulletin &amp; Review</em> 16 (2): 225–37. <a href="https://doi.org/10.3758/pbr.16.2.225">https://doi.org/10.3758/pbr.16.2.225</a>.</p>
</div>
<div id="section-ref-RN11406">
<p>Torchiano, Marco. 2017. “Effsize: Efficient Effect Size Computation.” Journal Article. <em>R Package Version 0.7.1.</em> <a href="%20%20https://CRAN.R-project.org/package=effsize">https://CRAN.R-project.org/package=effsize</a>.</p>
</div>
<div id="section-ref-RN11407">
<p>Wickham, Hadley. 2017. “Tidyverse: Easily Install and Load ’Tidyverse’ Packages.” Journal Article. <em>R Package Version 1.1.1.</em> <a href="https://CRAN.R-project.org/package=tidyverse">https://CRAN.R-project.org/package=tidyverse</a>.</p>
</div>
<div id="section-ref-RN11404">
<p>Wickham, Hadley, and G. Grolemund. 2017. <em>R for Data Science</em>. Book. Sebastopol, CA: O’Reilly.</p>
</div>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="section-fn1"><p>Basically you can use this tutorial for teaching and non-profit activities but do not meddle with it or claim it as your own work.<a href="#section-fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">adventr: hypothesis testing</h2>
<h4 class="author"><em>Andy Field</em></h4>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
